import type { Metadata } from "next";
import CodeBlock from "@/components/CodeBlock";
import Callout from "@/components/Callout";
import Playground from "@/components/Playground";

export const metadata: Metadata = {
  title: "Spacing Utilities",
  description: "Margin, padding, and gap utilities on a 0–5 scale, plus directional, axis, responsive, !important, and arbitrary-value variants.",
  alternates: { canonical: "/utilities/spacing" },
};

const SCALE = [
  { key: "0", value: "0" },
  { key: "1", value: "0.25rem" },
  { key: "2", value: "0.5rem" },
  { key: "3", value: "1rem" },
  { key: "4", value: "1.5rem" },
  { key: "5", value: "3rem" },
  { key: "auto", value: "auto" },
];

const PREFIXES = [
  { prefix: "m", props: "margin" },
  { prefix: "mt", props: "margin-top" },
  { prefix: "mb", props: "margin-bottom" },
  { prefix: "ms", props: "margin-left" },
  { prefix: "me", props: "margin-right" },
  { prefix: "ml", props: "margin-left (alias of ms)" },
  { prefix: "mr", props: "margin-right (alias of me)" },
  { prefix: "mx", props: "margin-left + margin-right" },
  { prefix: "my", props: "margin-top + margin-bottom" },
  { prefix: "p", props: "padding" },
  { prefix: "pt", props: "padding-top" },
  { prefix: "pb", props: "padding-bottom" },
  { prefix: "ps", props: "padding-left" },
  { prefix: "pe", props: "padding-right" },
  { prefix: "pl", props: "padding-left (alias of ps)" },
  { prefix: "pr", props: "padding-right (alias of pe)" },
  { prefix: "px", props: "padding-left + padding-right" },
  { prefix: "py", props: "padding-top + padding-bottom" },
];

export default function SpacingPage() {
  return (
    <div>
      <h1 className="fw-bold mb-2">Spacing</h1>
      <p className="text-muted mb-4">
        Margin, padding, and gap utilities — all built from the same generator loop across 14
        prefixes, so what&apos;s true for one is true for (almost) all of them. This page covers
        every variant, including the ones that look valid but silently do nothing.
      </p>

      <h2 className="mt-5 mb-3">The scale</h2>
      <p className="mb-3">
        Margin and padding share one scale, <code>0–5</code> plus <code>auto</code>:
      </p>
      <div className="table-responsive mb-4">
        <table className="table table-sm">
          <thead>
            <tr><th>Key</th><th>Value</th></tr>
          </thead>
          <tbody>
            {SCALE.map((s) => (
              <tr key={s.key}>
                <td><code>{s.key}</code></td>
                <td><code>{s.value}</code></td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <Callout variant="warning" title="The scale stops at 5 — there is no 6, 7, or beyond">
        <code>m-6</code>, <code>p-7</code>, <code>px-6</code> — none of these exist, at any
        prefix. They have no brackets, so they don&apos;t fall back to the arbitrary matcher
        either; the lookup just fails and nothing is emitted, no warning. See{" "}
        <a href="#scale-ceiling">Scale ceiling</a> below for a live demo.
      </Callout>

      <h2 className="mt-5 mb-3">The 14 prefixes</h2>
      <p className="mb-3">
        Every prefix below shares the same scale, the same responsive variants, and the same{" "}
        <code>!important</code> form — they&apos;re generated by one loop over this exact list:
      </p>
      <div className="table-responsive mb-4">
        <table className="table table-sm">
          <thead>
            <tr><th>Prefix</th><th>CSS propert{"y/ies"}</th></tr>
          </thead>
          <tbody>
            {PREFIXES.map((p) => (
              <tr key={p.prefix}>
                <td><code>{p.prefix}</code></td>
                <td>{p.props}</td>
              </tr>
            ))}
          </tbody>
        </table>
      </div>
      <Callout variant="tip" title="ms/me/ps/pe are physical, not RTL-logical">
        Despite the Bootstrap-5-style naming (start/end), these map straight to left/right —
        there&apos;s no direction flip under an RTL document. <code>ml</code>/<code>mr</code>/
        <code>pl</code>/<code>pr</code> are plain aliases of the same properties, included for
        anyone arriving from Tailwind.
      </Callout>

      <h2 className="mt-5 mb-3">Margin &amp; padding</h2>
      <Playground classes={["m-0", "m-1", "m-2", "m-3", "m-4", "m-5", "m-auto"]} previewLabel="margin" />
      <Playground classes={["p-0", "p-1", "p-2", "p-3", "p-4", "p-5"]} previewLabel="padding" />

      <h2 className="mt-5 mb-3">Directional &amp; axis</h2>
      <Playground classes={["mt-3", "mb-3", "ms-3", "me-3", "mx-3", "my-3"]} previewLabel="margin" />
      <Playground classes={["pt-3", "pb-3", "ps-3", "pe-3", "px-3", "py-3"]} previewLabel="padding" />

      <h2 className="mt-5 mb-3">Auto margins</h2>
      <p className="mb-3">
        Every one of the 14 prefixes gets an <code>auto</code> entry from the same loop that
        builds the numeric scale. On the margin side that&apos;s all genuinely useful CSS —{" "}
        <code>ms-auto</code>/<code>me-auto</code> is the classic push-to-the-edge trick inside a
        flex row:
      </p>
      <Playground classes={["mt-auto", "mb-auto", "ms-auto", "me-auto", "mx-auto", "my-auto"]} />
      <CodeBlock
        lang="html"
        code={`<nav class="d-flex align-items-center">\n  <span>Logo</span>\n  <a class="ms-auto" href="/login">Log in</a>\n</nav>`}
      />
      <Callout variant="danger" title="p*-auto exists but is always dead — CSS padding has no auto">
        <code>p-auto</code>, <code>pt-auto</code>, <code>ps-auto</code>, <code>px-auto</code> —
        the same generator loop produces all of these, but <code>padding</code> doesn&apos;t
        accept <code>auto</code> as a value at all. Every one compiles to an invalid declaration
        the browser silently drops. Toggle both below — <code>p-auto</code> changes nothing on
        top of <code>p-3</code>:
      </Callout>
      <Playground classes={["p-3", "p-auto"]} />

      <h2 className="mt-5 mb-3">Physical aliases</h2>
      <Playground classes={["ml-3", "mr-3", "pl-3", "pr-3", "ml-auto", "mr-auto"]} />

      <h2 className="mt-5 mb-3">Responsive</h2>
      <p className="mb-3">
        Every prefix, every scale key (including <code>auto</code>), at every breakpoint:
      </p>
      <Playground classes={["m-sm-0", "mt-md-3", "px-lg-4", "py-xl-5", "ms-md-auto"]} />

      <h2 className="mt-5 mb-3">!important variant</h2>
      <p className="mb-3">
        Prefix any spacing class with <code>!</code> for an <code>!important</code> version —
        this is a framework-wide mechanism, not spacing-specific, but spacing is where you&apos;ll
        reach for it most (overriding a component&apos;s own padding, say):
      </p>
      <Playground classes={["!m-3", "!mt-0", "!px-2", "!py-4", "!ms-auto"]} />

      <h2 className="mt-5 mb-3">Arbitrary values</h2>
      <p className="mb-3">
        Any value in brackets works on any prefix — but there&apos;s a real distinction in what a
        multi-value declaration does depending on which prefix you use it on.
      </p>
      <h3 className="mt-4 mb-2">Single value — works on every prefix</h3>
      <Playground classes={["mt-[12px]", "ms-[2vw]", "px-[2rem]"]} />
      <h3 className="mt-4 mb-2">Negative values — the only way to get negative margin</h3>
      <p className="mb-3">
        There&apos;s no named negative-margin scale, so pulling an element outward always goes
        through arbitrary:
      </p>
      <Playground classes={["m-[-1rem]", "mt-[-8px]"]} />
      <h3 className="mt-4 mb-2">Multi-value — shorthand m-[...]/p-[...] only</h3>
      <Callout variant="warning" title="px-[10px_20px] is invalid — use p-[10px_20px] instead">
        Only the bare <code>m</code>/<code>p</code> map to the shorthand property (<code>margin</code>
        /<code>padding</code>), which accepts a two-value declaration. Every directional/axis
        prefix (<code>mt</code>, <code>px</code>, <code>py</code>, etc.) maps to one or two{" "}
        <em>longhand</em> properties, each of which only accepts a single value —{" "}
        <code>px-[10px_20px]</code> would apply the literal two-token string to both{" "}
        <code>padding-left</code> and <code>padding-right</code>, which is invalid CSS and gets
        silently dropped. Keep directional/axis arbitrary values to one token.
      </Callout>
      <Playground classes={["p-[10px_20px]", "m-[1rem_2rem]"]} />
      <h3 className="mt-4 mb-2">Responsive + !important compose with arbitrary too</h3>
      <Playground classes={["px-md-[2rem]", "!p-[10px_20px]"]} />

      <h2 className="mt-5 mb-3" id="scale-ceiling">Scale ceiling</h2>
      <p className="mb-3">
        Toggle <code>m-6</code>/<code>m-7</code> below on top of <code>m-5</code> — nothing
        changes, because neither class emits any CSS at all:
      </p>
      <Playground classes={["m-4", "m-5", "m-6", "m-7"]} />
      <p className="mb-3">Past the ceiling, arbitrary is the only way to go bigger:</p>
      <Playground classes={["m-5", "m-[4rem]", "m-[5rem]"]} />

      <h2 className="mt-5 mb-3">Gap</h2>
      <p className="mb-3">
        <code>gap</code>/<code>row-gap</code>/<code>col-gap</code> are also spacing — they set
        flex/grid item spacing rather than margin/padding, but share the same underlying{" "}
        <code>0–5</code> scale (built from a separate scale object with the same values).{" "}
        <strong>Unlike margin, there is no <code>auto</code> entry at all</strong> —{" "}
        <code>gap-auto</code> doesn&apos;t exist, since <code>gap: auto</code> isn&apos;t
        meaningful CSS the way <code>margin: auto</code> is. There&apos;s also no named{" "}
        <code>!important</code> variant — only the arbitrary form supports it.
      </p>
      <Playground classes={["gap-0", "gap-1", "gap-2", "gap-3", "gap-4", "gap-5"]} previewLabel="gap" />
      <Playground classes={["row-gap-3", "col-gap-3"]} previewLabel="row/col gap" />
      <h3 className="mt-4 mb-2">Responsive</h3>
      <Playground classes={["gap-md-3", "row-gap-lg-3", "col-gap-sm-2"]} />
      <h3 className="mt-4 mb-2">Arbitrary</h3>
      <p className="mb-3">
        <code>gap</code> is itself a shorthand (row + column), so it accepts a multi-value
        declaration — <code>row-gap</code>/<code>col-gap</code> don&apos;t, same rule as margin/
        padding above:
      </p>
      <Playground classes={["gap-[1rem_2rem]", "row-gap-[1rem]", "col-gap-[1rem]"]} />
      <h3 className="mt-4 mb-2">Responsive + !important</h3>
      <Playground classes={["gap-md-[1rem_2rem]", "!gap-[1rem]"]} />
      <h3 className="mt-4 mb-2">Same ceiling as margin/padding</h3>
      <Playground classes={["gap-5", "gap-6", "gap-auto"]} />

      <Callout variant="tip" title="Grid gutters (g/gx/gy) are a related but separate mechanism">
        <code>g</code>/<code>gx</code>/<code>gy</code> share the same <code>0–5</code> ceiling,
        but they set the <code>--st-gutter-x</code>/<code>--st-gutter-y</code> custom properties
        the grid system reads — not a <code>gap</code> property directly. They&apos;re covered on
        the <a href="/utilities/grid">Grid</a> page instead of here.
      </Callout>
    </div>
  );
}
